package com.tutorialDB;

// Generated 4 juin 2008 20:30:32 by Hibernate Tools 3.2.0.CR1

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private Integer idDept;
	private String nomDept;

	public Dept() {
	}

	public Dept(String nomDept) {
		this.nomDept = nomDept;
	}

	public Integer getIdDept() {
		return this.idDept;
	}

	public void setIdDept(Integer idDept) {
		this.idDept = idDept;
	}

	public String getNomDept() {
		return this.nomDept;
	}

	public void setNomDept(String nomDept) {
		this.nomDept = nomDept;
	}

}
