package com.tutorialDB;

// Generated 4 juin 2008 20:30:32 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

/**
 * Personnel generated by hbm2java
 */
public class Personnel implements java.io.Serializable {

	private Integer idPersonnel;
	private Integer idDept;
	private String nomPersonnel;
	private String prenomPersonnel;
	private Date dateNaissance;

	public Personnel() {
	}

	public Personnel(Integer idDept, String nomPersonnel,
			String prenomPersonnel, Date dateNaissance) {
		this.idDept = idDept;
		this.nomPersonnel = nomPersonnel;
		this.prenomPersonnel = prenomPersonnel;
		this.dateNaissance = dateNaissance;
	}

	public Integer getIdPersonnel() {
		return this.idPersonnel;
	}

	public void setIdPersonnel(Integer idPersonnel) {
		this.idPersonnel = idPersonnel;
	}

	public Integer getIdDept() {
		return this.idDept;
	}

	public void setIdDept(Integer idDept) {
		this.idDept = idDept;
	}

	public String getNomPersonnel() {
		return this.nomPersonnel;
	}

	public void setNomPersonnel(String nomPersonnel) {
		this.nomPersonnel = nomPersonnel;
	}

	public String getPrenomPersonnel() {
		return this.prenomPersonnel;
	}

	public void setPrenomPersonnel(String prenomPersonnel) {
		this.prenomPersonnel = prenomPersonnel;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

}
